In [ ]:
a = pd.read_csv('../data/gender/transactions.csv') 

descr_mcc = pd.read_csv('../data/gender/tr_mcc_codes.csv', sep=';')
descr_types = pd.read_csv('../data/gender/tr_types.csv', sep=';')

a = a.merge(descr_mcc, on='mcc_code', how='left').merge(descr_types, on='tr_type', how='left')\
        .fillna({'tr_description' : "", 'mcc_description' : ""})

a['description'] = a.mcc_description + " " +  a.tr_description

a.drop(columns = ['mcc_description', 'tr_description']).to_csv('../data/gender/transactions_d.csv')

In [6]:
import argparse
import datetime
import logging
import os
import pickle
from random import Random
import yaml
from tqdm.notebook import tqdm

import numpy as np
import time
import pandas as pd

from gensim.models import KeyedVectors
from huggingface_hub import hf_hub_download
from sentence_transformers import SentenceTransformer, util
import fasttext

from ptls.preprocessing.util import pd_hist
from dotsi import Dict
import re

logger = logging.getLogger(__name__)

In [11]:
a = pd.read_csv('../data/gender/transactions_d.csv')
a.head(2)

,customer_id,tr_datetime,mcc_code,tr_type,amount,term_id,description
0,39026145,0 10:23:26,4814,1030,-2245.92,NaN,"Звонки с использованием телефонов, считывающих..."
1,39026145,1 10:19:29,6011,7010,56147.89,NaN,Финансовые институты — снятие наличности автом...

In [10]:
a.drop(columns=['Unnamed: 0.1', 'Unnamed: 0']).to_csv('../data/gender/transactions_d.csv', index_label=False)

In [56]:
from sklearn.decomposition import PCA

from gensim.models import KeyedVectors
from huggingface_hub import hf_hub_download
from sentence_transformers import SentenceTransformer, util


class TextPreprocessor:
    def __init__(self, 
                 method, 
                 feature_names, 
                 enable_pca,  
                 compressed_dim=-1, 
                 saves_directory=None
                 ):
        self.compressed_dim = compressed_dim
        self.feature_names = feature_names
        self.enable_pca = enable_pca
        self.method = method
        if self.method == 'rubert_output':
            self.model = SentenceTransformer('sergeyzh/rubert-tiny-turbo')
            self.embedding_dim = 312
        elif self.method == 'avg_pooling_w2v':
            self.model = KeyedVectors.load_word2vec_format(hf_hub_download(repo_id="Word2vec/wikipedia2vec_ruwiki_20180420_300d", filename="ruwiki_20180420_300d.txt"))
            self.embedding_dim = 300
        elif self.method == 'avg_pooling_fasttext':
            self.model = fasttext.load_model(hf_hub_download(repo_id="facebook/fasttext-ru-vectors", filename="model.bin")) 
            self.embedding_dim = 300
        else:
            raise Exception('No method of text feature encoding with such name exists')

        self.pca_models = dict()
        if self.enable_pca:
            for fe in self.feature_names:
                self.pca_models[fe] =  PCA(n_components=self.compressed_dim)

        self.unk_str = None

    def calc_embeddings(self, X, idcol_name, fit_pca=True):
        ids = []
        for sample in X:
            ids.append(sample[idcol_name])
        
        embeds = dict()
        for fe in self.feature_names:
            def vclear(s):
                s = " ".join(s[fe])
                return re.sub(r"[^а-яА-Я0-9\s]+|\s{2,}", " ", s.lower()).strip().split(" ")

            if self.method == 'rubert_output':

                def get_emb(sample):
                    return self.model.encode(sample[fe])

                embeds[fe] = list(map(get_emb, X))
            elif self.method == 'avg_pooling_w2v':
                if self.unk_str is None:
                    vocabulary = list(set(np.concatenate(list(map(vclear, X)))) - {"", " "})
                    self.unk_str = self.unk_detection(vocabulary)

                def sclear(s):
                    sts = []
                    for st in s[fe]:
                        st = re.sub(r"[^а-яА-Я0-9\s]+|\s{2,}", " ", st.lower())
                        if self.unk_str != '':
                            st = re.sub(rf"{self.unk_str}", "unk", st)
                        sts.append(np.mean(self.model[*re.sub(r"\s+", " ", st).strip().split(" ")], axis=0))
                    return sts

                embeds[fe] = list(map(sclear, X))

            elif self.method == 'avg_pooling_fasttext':
                if self.unk_str is None:
                    vocabulary = list(set(np.concatenate(list(map(vclear, X)))) - {"", " "})
                    self.unk_str = self.unk_detection(vocabulary)

                def sclear(s):
                    sts = []
                    for st in s[fe]:
                        st = re.sub(r"[^а-яА-Я0-9\s]+|\s{2,}", " ", st.lower())
                        if self.unk_str != '':
                            st = re.sub(rf"{self.unk_str}", "unk", st)
                        sts.append(self.model.get_sentence_vector(re.sub(r"\s+", " ", st).strip()))
                    return sts

                embeds[fe] = list(map(sclear, X))

            if self.enable_pca:
                if fit_pca:
                    self.pca_models[fe].fit(np.concatenate(embeds[fe]))
                embeds[fe] = list(map(self.pca_models[fe].transform, embeds[fe]))

        return pd.DataFrame({idcol_name : ids} | embeds)

    def unk_detection(self, voc):
        unk_str = ""
        for w in voc:
            try:
                self.model[w]
            except:
                unk_str = unk_str + w + "|"
        return unk_str[:-1]

In [93]:
import torch
embeds_test.set_index('client_id').loc[embeds_test.client_id.sample(128).values, 'description'].values

array([array([[-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04],
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03],
              [-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04],
              ...,
              [ 1.35172198e-01,  9.20530172e-02,  2.69425594e-02, ...,
               -1.19488768e-02, -5.99096874e-03,  1.37084751e-02],
              [-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04],
              [-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04]])   ,
       array([[-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04],
              [-1.92619317e-01,  2.95137925e-02, -1.01710811e-01, ...,
                1.19556965e-03,  7.65141044e-04,  7.61257318e-05],
              [-1.95821387e-01,  8.24086497e-02, -1.58058974e-01, ...,
               -1.26875336e-03,  1.39057185e-04, -8.77881047e-04],
              ...,
              [-1.95821387e-01,  8.24086497e-02, -1.58058974e-01, ...,
               -1.26875336e-03,  1.39057185e-04, -8.77881047e-04],
              [ 2.18145992e-02, -1.02558488e-01, -2.01748837e-02, ...,
               -3.02414123e-03, -7.88552353e-02, -1.28880959e-02],
              [-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04]])   ,
       array([[-0.12845915, -0.11135804,  0.08511815, ..., -0.00371442,
                0.0031251 , -0.0101098 ],
              [-0.12262873, -0.07002141,  0.05861451, ..., -0.00809819,
                0.00629155, -0.00243054],
              [-0.12845915, -0.11135804,  0.08511815, ..., -0.00371442,
                0.0031251 , -0.0101098 ],
              ...,
              [-0.20593083, -0.13703145,  0.02127224, ..., -0.00197674,
                0.01740046,  0.00313569],
              [-0.12845915, -0.11135804,  0.08511815, ..., -0.00371442,
                0.0031251 , -0.0101098 ],
              [-0.12845915, -0.11135804,  0.08511815, ..., -0.00371442,
                0.0031251 , -0.0101098 ]])                             ,
       array([[-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03],
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03],
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03],
              ...,
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03],
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03],
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03]])   ,
       array([[ 2.81862725e-01, -2.57582307e-02, -1.33704271e-02, ...,
                2.83926065e-04,  3.06643510e-04, -9.93019782e-04],
              [ 1.68754266e-01,  2.75492079e-02,  1.79893549e-02, ...,
                4.19839875e-04,  4.67618086e-03, -1.71873059e-02],
              [ 1.29840082e-01,  4.89179066e-02,  1.86702132e-02, ...,
               -4.84062180e-02,  1.64222460e-02, -4.74652877e-04],
              ...,
              [-1.65026124e-01,  5.31739144e-02, -1.09309225e-01, ...,
                9.24252293e-04,  1.22596603e-02,  3.75978321e-04],
              [ 2.81862725e-01, -2.57582307e-02, -1.33704271e-02, ...,
                2.83926065e-04,  3.06643510e-04, -9.93019782e-04],
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03]])   ,
       array([[-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04],
              [-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04],
              [-1.23863380e-01, -1.08500700e-01,  5.59573810e-02, ...,
               -5.62626087e-03,  7.11905970e-03,  5.23465958e-03],
              ...,
              [-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04],
              [-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04],
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03]])   ,
       array([[-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03],
              [-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04],
              [-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04],
              ...,
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03],
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03],
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03]])   ,
       array([[-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03],
              [-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04],
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03],
              ...,
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03],
              [-1.23863380e-01, -1.08500700e-01,  5.59573810e-02, ...,
               -5.62626087e-03,  7.11905970e-03,  5.23465958e-03],
              [-1.30767836e-01, -1.84337838e-01,  7.35119959e-02, ...,
                2.00618015e-03, -8.70856438e-03, -9.71171027e-03]])   ,
       array([[-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04],
              [-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04],
              [-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04],
              ...,
              [-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04],
              [-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04],
              [-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04]])   ,
       array([[-1.86027959e-01,  5.00168691e-02, -1.05592009e-01, ...,
               -4.69694670e-03, -9.78261024e-04, -4.10693758e-04],
              [-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04],
              [-1.86027959e-01,  5.00168691e-02, -1.05592009e-01, ...,
               -4.69694670e-03, -9.78261024e-04, -4.10693758e-04],
              ...,
              [-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04],
              [ 1.05638810e-01,  6.27882279e-02, -1.43405078e-02, ...,
               -1.31152055e-03, -2.85787160e-03, -2.00492290e-03],
              [ 2.81862725e-01, -2.57582307e-02, -1.33704271e-02, ...,
                2.83926065e-04,  3.06643510e-04, -9.93019782e-04]])   ,
       array([[-1.63121004e-01, -1.32556273e-01,  3.73167212e-02, ...,
                1.02532131e-03, -2.24560859e-03, -1.00909324e-03],
              [-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04],
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03],
              ...,
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03],
              [-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04],
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03]])   ,
       array([[ 9.76715124e-02,  5.23388461e-02,  2.35078456e-02, ...,
               -3.98976042e-02,  1.79901551e-02,  1.74325824e-02],
              [ 2.81862725e-01, -2.57582307e-02, -1.33704271e-02, ...,
                2.83926065e-04,  3.06643510e-04, -9.93019782e-04],
              [-1.63121004e-01, -1.32556273e-01,  3.73167212e-02, ...,
                1.02532131e-03, -2.24560859e-03, -1.00909324e-03],
              ...,
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03],
              [-1.84846410e-01, -1.35072611e-01,  4.99059509e-02, ...,
               -7.14930126e-04,  9.19346616e-03, -7.61810643e-03],
              [-1.63121004e-01, -1.32556273e-01,  3.73167212e-02, ...,
                1.02532131e-03, -2.24560859e-03, -1.00909324e-03]])   ,
       array([[-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03],
              [ 2.85227606e-01, -1.25010959e-01, -1.04329483e-01, ...,
               -1.86856641e-03,  1.27870402e-04, -1.23956573e-04],
              [ 2.00568490e-01,  4.63289212e-02,  6.47174351e-02, ...,
                6.10340693e-04, -6.96451652e-04, -5.13026801e-03],
              ...,
              [-1.92619317e-01,  2.95137925e-02, -1.01710811e-01, ...,
                1.19556965e-03,  7.65141044e-04,  7.61257318e-05],
              [-1.95821387e-01,  8.24086497e-02, -1.58058974e-01, ...,
               -1.26875336e-03,  1.39057185e-04, -8.77881047e-04],
              [-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04]])   ,
       array([[-1.51894230e-01, -9.99197321e-02,  5.80045751e-02, ...,
               -3.07966766e-03,  7.59265564e-03, -2.20828795e-03],
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03],
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03],
              ...,
              [-1.22628728e-01, -7.00214127e-02,  5.86145136e-02, ...,
               -8.09818572e-03,  6.29155197e-03, -2.43054333e-03],
              [ 1.25958105e-01,  2.96499363e-02,  1.55592879e-03, ...,
                2.73888242e-04, -2.24099978e-04,  5.29910200e-04],
              [ 1.25958105e-01,  2.96499363e-02,  1.55592879e-03, ...,
                2.73888242e-04, -2.24099978e-04,  5.29910200e-04]])   ,
       array([[ 1.28370114e-01,  1.03834577e-02, -6.28993936e-02, ...,
               -6.57024791e-04, -1.05499202e-03, -6.98930667e-04],
              [-1.95821387e-01,  8.24086497e-02, -1.58058974e-01, ...,
               -1.26875336e-03,  1.39057185e-04, -8.77881047e-04],
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03],
              ...,
              [ 2.85227606e-01, -1.25010959e-01, -1.04329483e-01, ...,
               -1.86856641e-03,  1.27870402e-04, -1.23956573e-04],
              [ 1.28370114e-01,  1.03834577e-02, -6.28993936e-02, ...,
               -6.57024791e-04, -1.05499202e-03, -6.98930667e-04],
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03]])   ,
       array([[-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03],
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03],
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03],
              ...,
              [-1.65026124e-01,  5.31739144e-02, -1.09309225e-01, ...,
                9.24252293e-04,  1.22596603e-02,  3.75978321e-04],
              [ 2.29565241e-01, -3.98891564e-02, -7.06783238e-02, ...,
                3.54907107e-03, -1.99834116e-03,  3.24711353e-03],
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03]])   ,
       array([[-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03],
              [-1.92619317e-01,  2.95137925e-02, -1.01710811e-01, ...,
                1.19556965e-03,  7.65141044e-04,  7.61257318e-05],
              [ 2.85227606e-01, -1.25010959e-01, -1.04329483e-01, ...,
               -1.86856641e-03,  1.27870402e-04, -1.23956573e-04],
              ...,
              [-1.95821387e-01,  8.24086497e-02, -1.58058974e-01, ...,
               -1.26875336e-03,  1.39057185e-04, -8.77881047e-04],
              [-1.77520080e-01,  7.90321322e-02, -1.38611230e-01, ...,
                4.96327753e-03, -7.86548158e-03,  2.50907228e-03],
              [-1.91688483e-01,  1.05299728e-01, -1.59189798e-01, ...,
                9.69234335e-04, -1.15456251e-03,  5.97467421e-04]])   ,
       array([[-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03],
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03],
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03],
              ...,
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03],
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03],
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03]])   ,
       array([[-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04],
              [-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04],
              [-1.65026124e-01,  5.31739144e-02, -1.09309225e-01, ...,
                9.24252293e-04,  1.22596603e-02,  3.75978321e-04],
              ...,
              [-1.65026124e-01,  5.31739144e-02, -1.09309225e-01, ...,
                9.24252293e-04,  1.22596603e-02,  3.75978321e-04],
              [-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04],
              [-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04]])   ,
       array([[-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03],
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03],
              [-1.84846410e-01, -1.35072611e-01,  4.99059509e-02, ...,
               -7.14930126e-04,  9.19346616e-03, -7.61810643e-03],
              ...,
              [ 2.39597146e-01,  3.93945235e-02,  4.63938072e-02, ...,
               -9.00141207e-03,  1.29921962e-04,  3.75486772e-04],
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03],
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03]])   ,
       array([[ 1.05638810e-01,  6.27882279e-02, -1.43405078e-02, ...,
               -1.31152055e-03, -2.85787160e-03, -2.00492290e-03],
              [-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04],
              [-1.84846410e-01, -1.35072611e-01,  4.99059509e-02, ...,
               -7.14930126e-04,  9.19346616e-03, -7.61810643e-03],
              ...,
              [ 1.05638810e-01,  6.27882279e-02, -1.43405078e-02, ...,
               -1.31152055e-03, -2.85787160e-03, -2.00492290e-03],
              [-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04],
              [-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04]])   ,
       array([[ 1.47622042e-01,  3.93315747e-02,  5.69890669e-03, ...,
               -1.61238464e-04,  2.79226695e-04, -1.53005583e-03],
              [ 1.47622042e-01,  3.93315747e-02,  5.69890669e-03, ...,
               -1.61238464e-04,  2.79226695e-04, -1.53005583e-03],
              [ 1.47622042e-01,  3.93315747e-02,  5.69890669e-03, ...,
               -1.61238464e-04,  2.79226695e-04, -1.53005583e-03],
              ...,
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03],
              [ 1.05638810e-01,  6.27882279e-02, -1.43405078e-02, ...,
               -1.31152055e-03, -2.85787160e-03, -2.00492290e-03],
              [ 1.05638810e-01,  6.27882279e-02, -1.43405078e-02, ...,
               -1.31152055e-03, -2.85787160e-03, -2.00492290e-03]])   ,
       array([[-1.63121004e-01, -1.32556273e-01,  3.73167212e-02, ...,
                1.02532131e-03, -2.24560859e-03, -1.00909324e-03],
              [-1.65026124e-01,  5.31739144e-02, -1.09309225e-01, ...,
                9.24252293e-04,  1.22596603e-02,  3.75978321e-04],
              [-1.63121004e-01, -1.32556273e-01,  3.73167212e-02, ...,
                1.02532131e-03, -2.24560859e-03, -1.00909324e-03],
              ...,
              [-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04],
              [-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04],
              [-1.63121004e-01, -1.32556273e-01,  3.73167212e-02, ...,
                1.02532131e-03, -2.24560859e-03, -1.00909324e-03]])   ,
       array([[-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,
               -1.40721383e-04,  1.81734577e-04, -1.55893669e-04],
              [-1.92619317e-01,  2.95137925e-02, -1.01710811e-01, ...,
                1.19556965e-03,  7.65141044e-04,  7.61257318e-05],
              [-1.37377105e-01, -1.70584869e-01,  9.52987283e-02, ...,
                1.68201910e-04, -2.53489091e-04,  1.10432673e-03],
              ...,
              [-4.39592108e-02,  1.85188207e-01,  1.17737938e-01, ...,

In [72]:
embeds_test.client_id.sample(128).values

array([24102800, 80378441, 56455029, 48753673, 46549491, 22358256,
       37632574, 18523734, 75346132, 44582602, 61092521, 43941597,
       66517978, 56661668, 50598019, 17168015,  8356198, 59461135,
       50628612,    28753, 61386658, 74823918,  2532836, 37466831,
       18932060, 75131411, 59585814, 14548818, 45106113, 12284205,
       49663929,   555494, 22450434, 24039668,   418693, 50723196,
        4613012, 56404702, 78210149, 34036744, 33533787, 21702278,
       24262944, 27391749, 57818455, 93818432, 62131392, 85686490,
       44963302, 96824387, 99915912, 20931581, 39122979, 35111431,
       45229256, 34174139, 23481237, 38392545, 40224781, 83605292,
       66206996, 66418902, 71100796, 15971667, 85564481, 22380244,
       28006767, 74302740, 31421357, 75278479, 95812175, 38155492,
       82876786, 97753724, 26120775, 50426364, 89537039, 22490949,
       55878885, 42665801, 25605832, 45149703, 77091333, 92100571,
       61385271, 25967949,  3592058, 50339535, 96237837, 98827945,
       85490501, 38679759, 61628007,  6085926,   312146, 42178458,
       87222013, 75445093,  1136140, 13857434, 16167490, 11963965,
       91977740, 70302931, 33455666, 86236687, 70148734, 19149664,
       38548792, 63145287,  6352651,  5413522, 34584581, 38707022,
       37854469, 39270809, 58760290, 32859557, 34156704, 62181901,
       59349430, 42886037, 53922199, 32508187, 81061748, 39408065,
       36305254, 14300407], dtype=int64)

In [10]:
from sklearn.model_selection import train_test_split
with open(f"../coles_prep_datasets/baseline_with_text_dataset_gender.pkl", "rb") as fl:
            dataset = pickle.load(fl)

train, test = train_test_split(dataset, test_size=0.1, random_state=42)

In [45]:
ids = []
for sample in train:
    ids.append(sample['client_id'])

In [57]:
text_prep = TextPreprocessor('avg_pooling_fasttext', ['description'], enable_pca=True, compressed_dim=48)

In [59]:
#bert 1043/100
#v2w 266/19
#ft 285/20

tt = time.time()
embeds = text_prep.calc_embeddings(train, 'client_id', fit_pca=True)
time.time() - tt

285.0577356815338

In [61]:
tt = time.time()
embeds_test = text_prep.calc_embeddings(test, 'client_id', fit_pca=False)
time.time() - tt

20.72563409805298

In [54]:
{1:2} | {3:4, 5:6}

{1: 2, 3: 4, 5: 6}

In [33]:
pd.DataFrame({'client_id' : ids, 'description_emb' : embeds}).head(3)

   client_id                                    description_emb
0   78833879  [[0.38614854, 0.0028899945, 0.006633103, 0.013...
1    6710884  [[-0.25542307, -0.24894574, -0.20159115, -0.00...
2   11032699  [[-0.06324831, 0.41056132, -0.20175041, -0.017...

In [13]:
model = SentenceTransformer('sergeyzh/rubert-tiny-turbo')
model

SentenceTransformer(
  (0): Transformer({'max_seq_length': 2048, 'do_lower_case': False}) with Transformer model: BertModel
  (1): Pooling({'word_embedding_dimension': 312, 'pooling_mode_cls_token': True, 'pooling_mode_mean_tokens': False, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Normalize()
)

In [18]:
ids = []
for el in tqdm(dataset):
    ids.append(el['client_id'])

  0%|          | 0/15000 [00:00<?, ?it/s]

In [28]:
np.stack([np.array(ids).reshape(-1, 1), embeds])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (15000,) + inhomogeneous part.

In [14]:
FE = 'description'

def get_emb(sample):
    return model.encode(sample[FE])

embeds = list(map(get_emb, dataset))

In [16]:
embeds[0]

array([[ 0.02567611,  0.01060615,  0.01709403, ...,  0.02607744,
         0.04172674, -0.03507769],
       [ 0.02567614,  0.01060615,  0.01709399, ...,  0.02607744,
         0.04172675, -0.03507769],
       [ 0.01457031, -0.0086526 , -0.00497847, ..., -0.02990391,
         0.07487129, -0.02889231],
       ...,
       [ 0.02567614,  0.01060615,  0.01709399, ...,  0.02607744,
         0.04172675, -0.03507769],
       [ 0.02567611,  0.01060615,  0.01709403, ...,  0.02607744,
         0.04172674, -0.03507769],
       [ 0.02567614,  0.01060615,  0.01709399, ...,  0.02607744,
         0.04172675, -0.03507769]], dtype=float32)

In [6]:
n_batches = 600

bs = a.shape[0] // n_batches + 1
print(bs)
embeds = []

embeds.append(model.encode(a.description.values[bs * i : min(bs * (i + 1), a.shape[0])]))

11416

  0%|          | 0/600 [00:00<?, ?it/s]

KeyboardInterrupt

In [50]:
model = KeyedVectors.load_word2vec_format(hf_hub_download(repo_id="Word2vec/nlpl_183", filename="model.bin"), binary=True, unicode_errors="ignore")

In [29]:
model = KeyedVectors.load_word2vec_format(hf_hub_download(repo_id="Word2vec/wikipedia2vec_ruwiki_20180420_300d", filename="ruwiki_20180420_300d.txt"))

In [31]:
def unk_detection(voc):
    unk_str = ""
    for w in voc:
        try:
            model[w]
        except:
            unk_str = unk_str + w + "|"
    return unk_str[:-1]

In [39]:
def vclear(s):
    s = " ".join(s['description'])
    return re.sub(r"[^а-яА-Я0-9\s]+|\s{2,}", " ", s.lower()).strip().split(" ")

vocabulary = list(set(np.concatenate(list(map(vclear, dataset)))) - {"", " "})
unk_str = unk_detection(vocabulary)

UNK_STR = unk_str

In [40]:
unk_str

'микрофильмирующее|фотокопировальное|ортодонтисты|фотоприборов|автогрузоперевозки|попереезду|билльярд|лабороторное|дальные|беспошлинные|салоты|разжиженный|комиссионки|\xa0с|превыш|обивочный|овердрафте|веломагазины'

In [46]:
POOLING_FUNC = lambda x: np.mean(x, axis=0)

def sclear(s):
    sts = []
    for st in s['description']:
        st = re.sub(r"[^а-яА-Я0-9\s]+|\s{2,}", " ", st.lower())
        if UNK_STR != '':
            st = re.sub(rf"{UNK_STR}", "unk", st)
        sts.append(POOLING_FUNC(model[*re.sub(r"\s+", " ", st).strip().split(" ")]))
    return sts

In [47]:
tt = time.time()
embeds = list(map(sclear, dataset))
time.time() - tt

221.76157331466675

In [162]:
a.description.shape

(6849346,)

In [32]:
with open('../data/gender/description_emb_w2v.pkl', 'wb') as fl:
    pickle.dump(embeds, fl)

In [52]:
model.get_sentence_vector('привет пока')

AttributeError: 'KeyedVectors' object has no attribute 'get_sentence_vector'

In [8]:
from icu_tokenizer import Tokenizer
tokenizer = Tokenizer(lang='ru')

tokenizer.tokenize('Мама мыла раму/дверь')

['Мама', 'мыла', 'раму', '/', 'дверь']

In [13]:
tokenizer.tokenize(" ".join(a.description.values))[:1000]

['Звонки',
 'с',
 'использованием',
 'телефонов',
 ',',
 'считывающих',
 'магнитную',
 'ленту',
 'Оплата',
 'услуги',
 '.',
 'Банкоматы',
 'СБ',
 'РФ',
 'Финансовые',
 'институты',
 '—',
 'снятие',
 'наличности',
 'автоматически',
 'Взнос',
 'наличных',
 'через',
 'АТМ',
 '(',
 'в',
 'своем',
 'тер.банке',
 ')',
 'Денежные',
 'переводы',
 'Списание',
 'с',
 'карты',
 'по',
 'операции',
 '“',
 'перевода',
 'с',
 'карты',
 'на',
 'карту',
 '”',
 'через',
 'АТМ',
 '(',
 'в',
 'пределах',
 'одного',
 'тер.банка',
 ')',
 'Различные',
 'продовольственные',
 'магазины',
 '—',
 'рынки',
 ',',
 'магазины',
 'со',
 'спец',
 '-',
 'ассортиментом',
 ',',
 'продажа',
 'полуфабрикатов',
 ',',
 'фирменных',
 'блюд',
 ',',
 'продажа',
 'с',
 'помощью',
 'торговых',
 'автоматов',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'СБ',
 'РФ',
 'Различные',
 'продовольственные',
 'магазины',
 '—',
 'рынки',
 ',',
 'магазины',
 'со',
 'спец',
 '-',
 'ассортиментом',
 ',',
 'продажа',
 'полуфабрикатов',
 ',',
 'фирменных',
 'блюд',
 ',',
 'продажа',
 'с',
 'помощью',
 'торговых',
 'автоматов',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'СБ',
 'РФ',
 'Станции',
 'техобслуживания',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'СБ',
 'РФ',
 'Различные',
 'продовольственные',
 'магазины',
 '—',
 'рынки',
 ',',
 'магазины',
 'со',
 'спец',
 '-',
 'ассортиментом',
 ',',
 'продажа',
 'полуфабрикатов',
 ',',
 'фирменных',
 'блюд',
 ',',
 'продажа',
 'с',
 'помощью',
 'торговых',
 'автоматов',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'СБ',
 'РФ',
 'Товары',
 'для',
 'дома',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'СБ',
 'РФ',
 'Различные',
 'продовольственные',
 'магазины',
 '—',
 'рынки',
 ',',
 'магазины',
 'со',
 'спец',
 '-',
 'ассортиментом',
 ',',
 'продажа',
 'полуфабрикатов',
 ',',
 'фирменных',
 'блюд',
 ',',
 'продажа',
 'с',
 'помощью',
 'торговых',
 'автоматов',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'СБ',
 'РФ',
 'Звонки',
 'с',
 'использованием',
 'телефонов',
 ',',
 'считывающих',
 'магнитную',
 'ленту',
 'Оплата',
 'услуги',
 '.',
 'Банкоматы',
 'СБ',
 'РФ',
 'Станции',
 'техобслуживания',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'СБ',
 'РФ',
 'Различные',
 'продовольственные',
 'магазины',
 '—',
 'рынки',
 ',',
 'магазины',
 'со',
 'спец',
 '-',
 'ассортиментом',
 ',',
 'продажа',
 'полуфабрикатов',
 ',',
 'фирменных',
 'блюд',
 ',',
 'продажа',
 'с',
 'помощью',
 'торговых',
 'автоматов',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'СБ',
 'РФ',
 'Продажа',
 'электронного',
 'оборудования',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'СБ',
 'РФ',
 'Финансовые',
 'институты',
 '—',
 'снятие',
 'наличности',
 'автоматически',
 'Выдача',
 'наличных',
 'в',
 'АТМ',
 'Сбербанк',
 'России',
 'Звонки',
 'с',
 'использованием',
 'телефонов',
 ',',
 'считывающих',
 'магнитную',
 'ленту',
 'Оплата',
 'услуги',
 '.',
 'Банкоматы',
 'СБ',
 'РФ',
 'Различные',
 'продовольственные',
 'магазины',
 '—',
 'рынки',
 ',',
 'магазины',
 'со',
 'спец',
 '-',
 'ассортиментом',
 ',',
 'продажа',
 'полуфабрикатов',
 ',',
 'фирменных',
 'блюд',
 ',',
 'продажа',
 'с',
 'помощью',
 'торговых',
 'автоматов',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'СБ',
 'РФ',
 'Финансовые',
 'институты',
 '—',
 'снятие',
 'наличности',
 'вручную',
 'Взнос',
 'наличных',
 'через',
 'POS',
 'Звонки',
 'с',
 'использованием',
 'телефонов',
 ',',
 'считывающих',
 'магнитную',
 'ленту',
 'Оплата',
 'услуги',
 '.',
 'Банкоматы',
 'СБ',
 'РФ',
 'Финансовые',
 'институты',
 '—',
 'снятие',
 'наличности',
 'автоматически',
 'Выдача',
 'наличных',
 'в',
 'АТМ',
 'Сбербанк',
 'России',
 'Финансовые',
 'институты',
 '—',
 'снятие',
 'наличности',
 'автоматически',
 'Выдача',
 'наличных',
 'в',
 'АТМ',
 'Сбербанк',
 'России',
 'Звонки',
 'с',
 'использованием',
 'телефонов',
 ',',
 'считывающих',
 'магнитную',
 'ленту',
 'Оплата',
 'услуги',
 '.',
 'Банкоматы',
 'СБ',
 'РФ',
 'Звонки',
 'с',
 'использованием',
 'телефонов',
 ',',
 'считывающих',
 'магнитную',
 'ленту',
 'Оплата',
 'услуги',
 '.',
 'Банкоматы',
 'СБ',
 'РФ',
 'Звонки',
 'с',
 'использованием',
 'телефонов',
 ',',
 'считывающих',
 'магнитную',
 'ленту',
 'Оплата',
 'услуги',
 '.',
 'Банкоматы',
 'СБ',
 'РФ',
 'Финансовые',
 'институты',
 '—',
 'снятие',
 'наличности',
 'автоматически',
 'Выдача',
 'наличных',
 'в',
 'АТМ',
 'Сбербанк',
 'России',
 'Финансовые',
 'институты',
 '—',
 'снятие',
 'наличности',
 'автоматически',
 'Выдача',
 'наличных',
 'в',
 'АТМ',
 'Сбербанк',
 'России',
 'Денежные',
 'переводы',
 'Списание',
 'с',
 'карты',
 'по',
 'операции',
 '“',
 'перевода',
 'с',
 'карты',
 'на',
 'карту',
 '”',
 'через',
 'АТМ',
 '(',
 'в',
 'пределах',
 'одного',
 'тер.банка',
 ')',
 'Станции',
 'техобслуживания',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'СБ',
 'РФ',
 'Станции',
 'техобслуживания',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'СБ',
 'РФ',
 'Универсальные',
 'магазины',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'Россия',
 'Универсальные',
 'магазины',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'Россия',
 'Универсальные',
 'магазины',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'Россия',
 'Универсальные',
 'магазины',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'Россия',
 'Продажа',
 'электронного',
 'оборудования',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'СБ',
 'РФ',
 'Станции',
 'техобслуживания',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'СБ',
 'РФ',
 'Товары',
 'для',
 'дома',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'СБ',
 'РФ',
 'Звонки',
 'с',
 'использованием',
 'телефонов',
 ',',
 'считывающих',
 'магнитную',
 'ленту',
 'Оплата',
 'услуги',
 '.',
 'Банкоматы',
 'СБ',
 'РФ',
 'Универсальные',
 'магазины',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'СБ',
 'РФ',
 'Станции',
 'техобслуживания',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'СБ',
 'РФ',
 'Звонки',
 'с',
 'использованием',
 'телефонов',
 ',',
 'считывающих',
 'магнитную',
 'ленту',
 'Оплата',
 'услуги',
 '.',
 'Банкоматы',
 'СБ',
 'РФ',
 'Звонки',
 'с',
 'использованием',
 'телефонов',
 ',',
 'считывающих',
 'магнитную',
 'ленту',
 'Оплата',
 'услуги',
 '.',
 'Банкоматы',
 'СБ',
 'РФ',
 'Аптеки',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'СБ',
 'РФ',
 'Звонки',
 'с',
 'использованием',
 'телефонов',
 ',',
 'считывающих',
 'магнитную',
 'ленту',
 'Оплата',
 'услуги',
 '.',
 'Банкоматы',
 'СБ',
 'РФ',
 'Финансовые',
 'институты',
 '—',
 'снятие',
 'наличности',
 'автоматически',
 'Взнос',
 'наличных',
 'через',
 'АТМ',
 '(',
 'в',
 'своем',
 'тер.банке',
 ')',
 'Звонки',
 'с',
 'использованием',
 'телефонов',
 ',',
 'считывающих',
 'магнитную',
 'ленту',
 'Оплата',
 'услуги',
 '.',
 'Банкоматы',
 'СБ',
 'РФ',
 'Станции',
 'техобслуживания',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'СБ',
 'РФ',
 'Универсальные',
 'магазины',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'Россия',
 'Универсальные',
 'магазины',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'Россия',
 'Различные',
 'продовольственные',
 'магазины',
 '—',
 'рынки',
 ',',
 'магазины',
 'со',
 'спец',
 '-',
 'ассортиментом',
 ',',
 'продажа',
 'полуфабрикатов',
 ',',
 'фирменных',
 'блюд',
 ',',
 'продажа',
 'с',
 'помощью',
 'торговых',
 'автоматов',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'Россия',
 'Бакалейные',
 'магазины',
 ',',
 'супермаркеты',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'Россия',
 'Различные',
 'продовольственные',
 'магазины',
 '—',
 'рынки',
 ',',
 'магазины',
 'со',
 'спец',
 '-',
 'ассортиментом',
 ',',
 'продажа',
 'полуфабрикатов',
 ',',
 'фирменных',
 'блюд',
 ',',
 'продажа',
 'с',
 'помощью',
 'торговых',
 'автоматов',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'Россия',
 'Различные',
 'продовольственные',
 'магазины',
 '—',
 'рынки',
 ',',
 'магазины',
 'со',
 'спец',
 '-',
 'ассортиментом',
 ',',
 'продажа',
 'полуфабрикатов',
 ',',
 'фирменных',
 'блюд',
 ',',
 'продажа',
 'с',
 'помощью',
 'торговых',
 'автоматов',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'Россия',
 'Различные',
 'продовольственные',
 'магазины',
 '—',
 'рынки',
 ',',
 'магазины',
 'со',
 'спец',
 '-',
 'ассортиментом',
 ',',
 'продажа',
 'полуфабрикатов',
 ',',
 'фирменных',
 'блюд',
 ',',
 'продажа',
 'с',
 'помощью',
 'торговых',
 'автоматов',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'СБ',
 'РФ',
 'Различные',
 'продовольственные',
 'магазины',
 '—',
 'рынки',
 ',',
 'магазины',
 'со',
 'спец',
 '-',
 'ассортиментом',
 ',',
 'продажа',
 'полуфабрикатов',
 ',',
 'фирменных',
 'блюд',
 ',',
 'продажа',
 'с',
 'помощью',
 'торговых',
 'автоматов',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'СБ',
 'РФ',
 'Различные',
 'продовольственные',
 'магазины',
 '—',
 'рынки',
 ',',
 'магазины',
 'со',
 'спец',
 '-',
 'ассортиментом',
 ',',
 'продажа',
 'полуфабрикатов',
 ',',
 'фирменных',
 'блюд',
 ',',
 'продажа',
 'с',
 'помощью',
 'торговых',
 'автоматов',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'СБ',
 'РФ',
 'Различные',
 'продовольственные',
 'магазины',
 '—',
 'рынки',
 ',',
 'магазины',
 'со',
 'спец',
 '-',
 'ассортиментом',
 ',',
 'продажа',
 'полуфабрикатов',
 ',',
 'фирменных',
 'блюд',
 ',',
 'продажа',
 'с',
 'помощью',
 'торговых',
 'автоматов',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'СБ',
 'РФ',
 'Станции',
 'техобслуживания',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'СБ',
 'РФ',
 'Аптеки',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'СБ',
 'РФ',
 'Аптеки',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'СБ',
 'РФ',
 'Различные',
 'продовольственные',
 'магазины',
 '—',
 'рынки',
 ',',
 'магазины',
 'со',
 'спец',
 '-',
 'ассортиментом',
 ',',
 'продажа',
 'полуфабрикатов',
 ',',
 'фирменных',
 'блюд',
 ',',
 'продажа',
 'с',
 'помощью',
 'торговых',
 'автоматов',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'СБ',
 'РФ',
 'Финансовые',
 'институты',
 '—',
 'снятие',
 'наличности',
 'автоматически',
 'Выдача',
 'наличных',
 'в',
 'АТМ',
 'Сбербанк',
 'России',
 'Звонки',
 'с',
 'использованием',
 'телефонов',
 ',',
 'считывающих',
 'магнитную',
 'ленту',
 'Оплата',
 'услуги',
 '.',
 'Банкоматы',
 'СБ',
 'РФ',
 'Различные',
 'продовольственные',
 'магазины',
 '—',
 'рынки',
 ',',
 'магазины',
 'со',
 'спец',
 '-',
 'ассортиментом',
 ',',
 'продажа',
 'полуфабрикатов',
 ',',
 'фирменных',
 'блюд',
 ',',
 'продажа',
 'с',
 'помощью',
 'торговых',
 'автоматов',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'СБ',
 'РФ',
 'Различные',
 'продовольственные',
 'магазины',
 '—',
 'рынки',
 ',',
 'магазины',
 'со',
 'спец',
 '-',
 'ассортиментом',
 ',',
 'продажа',
 'полуфабрикатов',
 ',',
 'фирменных',
 'блюд',
 ',',
 'продажа',
 'с',
 'помощью',
 'торговых',
 'автоматов',
 'Покупка',
 '.',
 'POS',
 'ТУ',
 'СБ',
 'РФ',
 'Звонки',
 'с',
 'использованием',
 'телефонов',
 ',',
 'считывающих',
 'магнитную',
 'ленту',
 'Оплата',
 'услуги',
 '.',
 'Банкоматы',
 'СБ',
 'РФ',
 'Различные',
 'продовольственные',
 'магазины',
 '—',
 'рынки',
 ',',
 'магазины']

In [33]:
model = fasttext.load_model(hf_hub_download(repo_id="facebook/fasttext-ru-vectors", filename="model.bin"))

In [38]:
def vclear(s):
    return re.sub(r"[^а-яА-Я0-9\s]+|\s{2,}", " ", s.lower()).strip().split(" ")

vocabulary = list(set(vclear(" ".join(a.description.values))) - {"", " "})
unk_str = unk_detection(vocabulary)

UNK_STR = unk_str

In [86]:
#fasttext pooling: avg(l2(w1) ... l2(wn)) | wi : l2(wi) > 0
#POOLING_FUNC = lambda x: np.mean(x, axis=0)

def sclear(s):
    s = re.sub(r"[^а-яА-Я0-9\s]+|\s{2,}", " ", s.lower())
    if UNK_STR != '':
        s = re.sub(rf"{UNK_STR}", "unk", s)
    return model.get_sentence_vector(re.sub(r"\s+", " ", s).strip())

In [87]:
tt = time.time()
embeds = a.description.apply(sclear)
time.time() - tt

207.3992931842804

In [75]:
model.get_word_vector('привет') - model.get_sentence_vector('привет')

array([-6.15190715e-03,  1.45997386e-03,  6.65750355e-03,  3.42515483e-03,
       -1.40691083e-03,  3.34920362e-03, -2.58298032e-03, -3.97892669e-03,
        3.16701480e-05, -3.39646125e-04, -6.67248666e-03, -5.93264028e-03,
       -4.92756814e-03, -3.66312265e-03,  2.28953920e-03,  3.78040597e-03,
        1.81317679e-04,  1.06833056e-02,  3.89794260e-03, -8.88168067e-03,
        7.08658993e-03,  4.98021767e-03, -1.92857906e-03, -4.62485105e-03,
       -2.11540051e-03, -8.18870030e-04,  2.92108767e-03, -4.52553481e-03,
       -4.18835878e-03, -3.68727371e-03, -3.29165906e-03, -5.33176586e-03,
       -1.44692603e-03, -1.34378672e-02, -3.21744010e-03,  2.79212371e-03,
        9.85278189e-03,  8.92252475e-03, -2.95028277e-03,  1.05811805e-02,
        8.59758258e-03, -5.59357926e-03,  1.66582689e-03, -1.15350471e-04,
        6.83879107e-03, -9.85962152e-03,  7.71176815e-03,  6.14222139e-04,
       -4.21479344e-03,  5.47670946e-03,  1.71641074e-03, -3.76369059e-03,
       -4.56809253e-03,  4.69206646e-03,  8.69580545e-04, -5.34310564e-03,
        2.26139789e-04, -4.66427580e-03,  1.69129111e-03, -3.15023959e-03,
       -8.66761431e-04, -8.38726014e-03, -2.83991359e-03,  4.68838587e-03,
        2.89244391e-03,  3.96936014e-03, -4.71507385e-03,  2.68122368e-03,
       -5.46555221e-03, -3.40297446e-03,  1.16554573e-02, -1.99561566e-03,
        4.89596277e-03,  5.58995083e-03,  4.57115471e-03,  6.02167100e-03,
        4.13724687e-04,  3.61927599e-03,  8.44553113e-03,  3.58683988e-03,
       -4.40067798e-03, -2.00447440e-03, -3.07068927e-04,  8.87216069e-04,
        2.75359256e-04, -4.15441394e-03,  3.15658748e-03, -8.03959556e-04,
        5.29425219e-03,  2.04071775e-03,  3.54249030e-03, -6.16955757e-03,
        1.65733881e-03,  1.89058110e-03,  2.71185115e-03, -1.81749649e-03,
       -3.86543944e-03,  6.73905015e-03,  8.96947831e-03,  2.42127664e-03,
        2.56201625e-03, -1.04939472e-03,  1.60758570e-03,  7.77712464e-03,
       -4.10221983e-04,  6.89655542e-03,  3.77696753e-03, -6.95499033e-03,
        3.22676729e-04, -5.22870570e-03,  1.44442916e-03,  5.06510586e-03,
       -4.04607132e-03,  4.29651886e-03,  1.79145671e-03, -2.84014083e-03,
        2.03480385e-03,  7.13320822e-03, -4.26145270e-03, -2.78571062e-03,
        5.16900420e-03, -6.52597100e-03,  4.04743105e-03,  1.84848718e-03,
       -6.10087533e-04, -7.24938582e-05, -9.70856100e-03,  6.40469790e-03,
        1.31441280e-03, -1.02143660e-02, -6.42389059e-03, -2.86772149e-04,
       -2.95633450e-03,  1.83522515e-03, -2.21353583e-03, -2.44000368e-03,
       -2.84307078e-03, -4.55890968e-03,  6.49619102e-03, -1.84931234e-03,
       -7.45087862e-03, -4.42825630e-03, -7.15842843e-03,  6.61917776e-03,
        9.36736912e-03,  2.13281438e-03, -4.19109687e-03, -5.55894896e-03,
       -8.77914578e-03, -3.89603898e-03, -6.27380610e-03, -6.13796711e-03,
        1.20644122e-02,  8.56211409e-04,  3.47786769e-03, -3.09542939e-03,
       -5.20334765e-03, -2.13552266e-03, -5.80374897e-03,  3.35685536e-03,
        1.92262977e-03,  4.45287675e-03,  1.30381286e-02,  8.95516574e-03,
        1.20201427e-03,  7.86583871e-03, -3.84951010e-03, -8.54860991e-03,
       -5.17800450e-03,  1.42038800e-04, -2.36223079e-03,  1.45431329e-03,
       -6.39446080e-03, -1.88378431e-03,  6.41014427e-03, -4.94648889e-03,
        6.15431368e-03, -2.52264366e-03, -2.25234590e-03,  3.14197689e-03,
        1.47431623e-03, -2.16272473e-03, -9.65209678e-04,  6.21769577e-03,
       -4.93734702e-03, -8.24255496e-03,  2.78774416e-04, -1.92469731e-03,
       -5.53512573e-03, -4.14061174e-03,  1.40438788e-03, -8.75718892e-04,
       -2.57395953e-03, -6.81135803e-03,  5.13494015e-03, -4.03271243e-03,
       -3.00978310e-04, -3.41079663e-04,  1.97733566e-03, -5.77789173e-03,
        7.80025125e-03, -4.72229719e-03, -4.11371142e-03,  3.22451442e-03,
        5.34306094e-03, -3.59996920e-04,  3.54571268e-03, -5.67947701e-03,
       -2.38584913e-03,  3.19921644e-04, -9.61774960e-04,  1.96280517e-03,
       -1.12739485e-03, -6.70212507e-03,  9.94016230e-03, -7.39406794e-03,
       -5.79052791e-03, -9.59510915e-04,  1.50936395e-02,  1.68809108e-03,
       -7.31947366e-04,  1.82131678e-03, -1.26937311e-03, -1.03679299e-03,
        5.66982478e-03,  6.75202906e-03,  8.16550851e-03, -1.31420232e-03,
        2.94229388e-03,  3.84837389e-03, -2.56442698e-04,  6.54345006e-03,
       -5.68382069e-03, -2.13640183e-03, -1.40250623e-02, -3.02215293e-03,
        3.46675515e-03, -1.24914646e-02,  2.67260708e-03, -2.49394216e-04,
       -2.01066025e-03,  1.48691423e-03, -2.66823359e-03,  2.29045190e-03,
        9.80894268e-03,  1.11179985e-03, -7.59102404e-03, -1.17575750e-03,
       -4.51892614e-03, -7.57884234e-04, -7.16584176e-03,  4.56739962e-03,
       -2.18957849e-03,  2.24646367e-03,  9.89728607e-04,  3.94687057e-03,
        4.81582433e-03,  2.80711241e-03,  3.82000208e-03,  9.16182250e-03,
       -6.23555854e-04,  2.96343118e-04, -9.48574394e-03,  7.64177740e-03,
        7.19519705e-03,  3.01008672e-03,  3.07494774e-03, -9.43361782e-04,
        2.92473473e-03,  1.34044141e-03, -2.40829960e-03,  4.52656671e-03,
       -1.17463395e-02,  9.51603055e-03, -1.14969630e-03, -3.76196578e-03,
       -7.12823123e-03, -2.62429006e-03, -3.82376462e-03,  4.92104143e-03,
        5.32779377e-04, -6.75389171e-03, -7.19568133e-03, -2.13311985e-04,
       -1.68746896e-03,  2.66286917e-03, -2.40515172e-03, -4.85777855e-03,
       -5.91133907e-03,  2.95192376e-03,  2.56659463e-04,  2.69803964e-03,
        5.10970503e-03,  4.91353124e-03, -1.44891324e-04,  1.84679404e-03,
       -3.27812159e-05,  1.36132538e-03, -3.60687496e-04,  5.72467968e-03],
      dtype=float32)

In [83]:
def l2_norm(x):
   return np.sqrt(np.sum(x**2))

def get_normed(w):
    emb = model.get_word_vector(w)
    l2 = l2_norm(emb)
    return emb / l2

l2_norm(model.get_word_vector('стол'))

1.4886659

In [84]:
np.mean(np.array([get_normed('привет'), get_normed('мама'), get_normed('стол')]), axis=0) - model.get_sentence_vector('привет мама стол')

array([ 0.0000000e+00,  3.7252903e-09,  3.7252903e-09, -1.8626451e-09,
        3.7252903e-09, -8.3819032e-09,  3.7252903e-09,  3.7252903e-09,
        3.7252903e-09,  0.0000000e+00,  0.0000000e+00, -7.4505806e-09,
        5.5879354e-09,  9.3132257e-10, -7.4505806e-09,  0.0000000e+00,
        4.6566129e-10, -3.7252903e-09,  0.0000000e+00,  7.4505806e-09,
       -1.8626451e-09,  0.0000000e+00,  0.0000000e+00,  3.7252903e-09,
        0.0000000e+00,  5.5879354e-09, -5.5879354e-09,  0.0000000e+00,
       -3.7252903e-09,  0.0000000e+00, -1.8626451e-09,  1.8626451e-09,
       -3.7252903e-09,  3.7252903e-09,  0.0000000e+00,  2.3283064e-10,
       -3.7252903e-09,  7.4505806e-09,  7.4505806e-09, -7.4505806e-09,
        0.0000000e+00,  5.5879354e-09, -4.6566129e-09, -1.3969839e-09,
        3.7252903e-09,  1.0244548e-08, -3.7252903e-09,  3.7252903e-09,
        0.0000000e+00, -1.4901161e-08,  1.8626451e-09,  0.0000000e+00,
        3.7252903e-09, -1.3038516e-08,  0.0000000e+00,  0.0000000e+00,
       -7.4505806e-09,  4.6566129e-09,  3.7252903e-09, -3.7252903e-09,
        3.7252903e-09,  3.7252903e-09, -2.7939677e-09,  3.7252903e-09,
        1.8626451e-09,  0.0000000e+00, -3.7252903e-09,  1.8626451e-09,
        0.0000000e+00, -3.7252903e-09, -3.7252903e-09, -2.5611371e-09,
       -7.4505806e-09, -4.6566129e-09, -2.7939677e-09, -7.4505806e-09,
        4.6566129e-10,  3.7252903e-09,  7.4505806e-09, -5.5879354e-09,
        0.0000000e+00,  5.5879354e-09,  2.3283064e-09,  7.4505806e-09,
        7.4505806e-09,  0.0000000e+00,  0.0000000e+00, -2.5611371e-09,
        0.0000000e+00, -3.7252903e-09,  0.0000000e+00,  0.0000000e+00,
        1.8626451e-09, -7.4505806e-09, -5.5879354e-09,  4.6566129e-10,
        4.6566129e-09, -3.7252903e-09, -5.5879354e-09, -2.3283064e-09,
        3.7252903e-09,  0.0000000e+00,  0.0000000e+00, -7.4505806e-09,
        1.3969839e-09, -7.4505806e-09,  0.0000000e+00,  4.6566129e-10,
        5.5879354e-09,  6.5192580e-09,  0.0000000e+00, -7.4505806e-09,
        1.8626451e-09,  0.0000000e+00, -5.5879354e-09,  1.8626451e-09,
        3.7252903e-09, -7.4505806e-09,  1.8626451e-09,  0.0000000e+00,
       -5.5879354e-09,  0.0000000e+00, -2.7939677e-09,  0.0000000e+00,
        9.3132257e-10, -5.5879354e-09,  5.1222742e-09, -9.3132257e-09,
       -7.4505806e-09,  3.7252903e-09, -1.8626451e-09,  7.4505806e-09,
        1.8626451e-09,  1.3969839e-09,  1.8626451e-09,  0.0000000e+00,
       -3.7252903e-09, -3.7252903e-09,  4.8894435e-09,  0.0000000e+00,
        0.0000000e+00,  7.4505806e-09, -7.4505806e-09, -1.8626451e-09,
        1.4901161e-08, -3.6961865e-09,  0.0000000e+00,  1.8626451e-09,
       -7.4505806e-09,  3.7252903e-09,  8.3819032e-09,  3.7252903e-09,
        1.4901161e-08,  9.3132257e-10, -2.7939677e-09,  0.0000000e+00,
        2.7939677e-09,  0.0000000e+00,  0.0000000e+00, -9.3132257e-10,
       -4.6566129e-10, -4.8894435e-09,  0.0000000e+00, -1.8626451e-09,
        3.7252903e-09, -6.2282197e-09,  5.0058588e-09,  9.3132257e-09,
        5.5879354e-09,  9.3132257e-10,  4.8894435e-09,  3.7252903e-09,
       -1.1175871e-08,  0.0000000e+00,  0.0000000e+00,  2.7939677e-09,
        0.0000000e+00,  0.0000000e+00, -7.4505806e-09, -1.8626451e-09,
       -1.8626451e-09, -1.8626451e-09,  0.0000000e+00,  0.0000000e+00,
       -3.7252903e-09,  0.0000000e+00,  0.0000000e+00,  1.8626451e-09,
        0.0000000e+00,  1.8626451e-09,  7.4505806e-09,  1.4901161e-08,
        7.4505806e-09,  7.4505806e-09, -4.6566129e-09,  3.7252903e-09,
       -1.1175871e-08,  0.0000000e+00,  0.0000000e+00,  3.7252903e-09,
        0.0000000e+00, -7.4505806e-09,  5.5879354e-09, -3.7252903e-09,
        7.4505806e-09, -1.8626451e-09, -3.7252903e-09, -3.7252903e-09,
        3.7252903e-09,  5.5879354e-09,  0.0000000e+00,  0.0000000e+00,
        1.8626451e-09, -3.7252903e-09, -7.4505806e-09, -3.7252903e-09,
        1.8626451e-09,  0.0000000e+00, -7.4505806e-09, -9.3132257e-10,
        9.3132257e-10,  0.0000000e+00,  5.5879354e-09,  9.3132257e-10,
        0.0000000e+00, -3.7252903e-09,  0.0000000e+00,  0.0000000e+00,
        3.7252903e-09,  0.0000000e+00,  5.5879354e-09, -1.1175871e-08,
        4.6566129e-09,  0.0000000e+00,  7.4505806e-09,  3.7252903e-09,
        1.8626451e-09,  0.0000000e+00, -9.7788870e-09,  5.5879354e-09,
       -3.7252903e-09,  0.0000000e+00,  0.0000000e+00, -1.8626451e-09,
        0.0000000e+00, -2.3283064e-09,  4.6566129e-09, -3.7252903e-09,
        2.7939677e-09,  3.7252903e-09,  0.0000000e+00,  3.7252903e-09,
       -3.7252903e-09, -7.4505806e-09,  2.7939677e-09, -1.8626451e-09,
        7.4505806e-09, -9.3132257e-09,  0.0000000e+00,  7.4505806e-09,
        0.0000000e+00, -5.5879354e-09,  7.4505806e-09,  0.0000000e+00,
        0.0000000e+00, -1.1641532e-09,  7.4505806e-09,  1.8626451e-09,
        0.0000000e+00,  2.3283064e-09,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00, -3.7252903e-09, -2.4738256e-09,  0.0000000e+00,
        7.4505806e-09,  5.5879354e-09,  0.0000000e+00,  0.0000000e+00,
        1.4901161e-08,  3.7252903e-09,  1.1175871e-08,  7.4505806e-09,
        3.0267984e-09, -7.4505806e-09,  5.5879354e-09,  3.7252903e-09,
        1.8626451e-09, -6.2864274e-09, -1.8626451e-09,  2.7939677e-09,
        0.0000000e+00,  0.0000000e+00,  3.7252903e-09,  0.0000000e+00,
       -5.1222742e-09, -5.1222742e-09, -1.1641532e-09,  1.8626451e-09],
      dtype=float32)

In [65]:
with open('../data/gender/description_emb_fasttext.pkl', 'wb') as fl:
    pickle.dump(embeds, fl)

## PCA

In [39]:
with open('../data/gender/description_emb.pkl', 'wb') as fl:
    pickle.dump(embeds, fl)

In [42]:
from sklearn.decomposition import PCA

pca = PCA(n_components=100)
pca.fit(embeds)

PCA(n_components=100)

In [43]:
pca.explained_variance_ratio_

array([4.11983848e-01, 1.82683215e-01, 1.17359117e-01, 4.15447764e-02,
       3.65382247e-02, 2.58944314e-02, 1.96549576e-02, 1.84964575e-02,
       1.35569340e-02, 1.27284545e-02, 1.03534264e-02, 9.42146592e-03,
       8.53461586e-03, 7.71311671e-03, 6.33986108e-03, 6.18652347e-03,
       5.27257798e-03, 4.80531575e-03, 4.02716547e-03, 3.78971128e-03,
       3.45425378e-03, 3.18450201e-03, 2.62481021e-03, 2.53438717e-03,
       2.41325563e-03, 2.17695837e-03, 2.08504405e-03, 1.99661171e-03,
       1.70449843e-03, 1.68998551e-03, 1.55007816e-03, 1.43566006e-03,
       1.30059570e-03, 1.23281288e-03, 1.18375837e-03, 1.12457294e-03,
       1.08468160e-03, 9.97078838e-04, 9.95499548e-04, 8.47157440e-04,
       8.31813377e-04, 7.47600337e-04, 7.10582652e-04, 7.00251316e-04,
       6.73219678e-04, 6.44059386e-04, 5.91815449e-04, 5.79622632e-04,
       5.73611818e-04, 5.02045907e-04, 4.74327651e-04, 4.57427785e-04,
       4.15779272e-04, 4.12594032e-04, 4.01723431e-04, 3.82267259e-04,
       3.59757512e-04, 3.45473672e-04, 3.44003609e-04, 3.22862732e-04,
       2.93506280e-04, 2.80851091e-04, 2.77239160e-04, 2.64235394e-04,
       2.48119963e-04, 2.39318484e-04, 2.20098591e-04, 2.16787914e-04,
       2.03463060e-04, 1.91030849e-04, 1.87781770e-04, 1.83020747e-04,
       1.73170018e-04, 1.66866230e-04, 1.61590651e-04, 1.56504771e-04,
       1.45957863e-04, 1.34645394e-04, 1.29772234e-04, 1.24904851e-04,
       1.16648152e-04, 1.13643036e-04, 1.09830711e-04, 1.08833578e-04,
       1.05499646e-04, 1.00902595e-04, 9.75429866e-05, 9.34312047e-05,
       8.81400993e-05, 8.41089714e-05, 8.13939187e-05, 7.84880540e-05,
       7.46426012e-05, 7.16035938e-05, 6.92745380e-05, 6.43267049e-05,
       5.94286212e-05, 5.81902023e-05, 5.57518906e-05, 5.31168953e-05],
      dtype=float32)

In [44]:
pca.transform(embeds).shape

(6849346, 100)

In [3]:
from datetime import timedelta
import random

a['time'] = [i[-8:] for i in a.tr_datetime]

padded_time = a['tr_datetime'].str.pad(15, 'left', '0')
day_part = padded_time.str[:6].astype(float)
time_part = pd.to_datetime(padded_time.str[7:], format='%H:%M:%S').values.astype('int64') // 1e9
time_part = time_part % (24 * 60 * 60) / (24 * 60 * 60)

a.tr_datetime = day_part + time_part

a['date'] = [str(i + datetime.timedelta(days=random.randint(40000, 40600)))[:10] for i in pd.to_datetime(a.time, format='%H:%M:%S')]

In [34]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

class TimePreprocessor:
    def __init__(self, idcol, ordercol, datecol=None, timecol=None, mode='all', exclude_list=[]):
        """
        ordercol: must contain positive integers
        datecol: must contain transaction date in format of string YYYY-MM-DD
        timecol: must contain transaction time in format of string HH:MM:SS
        mode: 'all' - collect all features, 'cat' - collect categorical features, 'num' - collect numeric features
        """
        self.idcol = idcol
        self.ordercol = ordercol
        self.datecol = datecol
        self.timecol = timecol
        self.mode = mode

        self.cat_features = []
        self.num_features = []
        self.exclude_list = exclude_list

        self.scalers = dict()

    def time_to_seconds(self, t):
        h, m, s = map(int, t.split(':'))
        return h * 3600 + m * 60 + s

    def normalize(self, f):
        return  (X[self.ordercol] - X[self.ordercol].mean())/(X[self.ordercol].max() - X[self.ordercol].min())

    def fit(self, X):
        if self.ordercol is not None:
            ordercol_deltas = X.groupby(self.idcol)[self.ordercol].transform(lambda x: x.sort_values().diff()).fillna(1)
            first_values = X.groupby(self.idcol)[self.ordercol].agg('min')
            if (ordercol_deltas != 1.0).sum() != 0 or  (first_values == first_values.iloc[0]).sum() != 0:
                self.num_features.append('TIME_ordercol_num')
                scaler = MinMaxScaler()
                scaler.fit(X[self.ordercol].values.reshape(-1, 1))
                self.scalers['TIME_ordercol_num'] = scaler
                if X[self.ordercol].unique().shape[0] < 1000:
                    self.cat_features.append('TIME_ordercol_cat')

        if self.timecol is not None:
            X['time_seconds'] = X[self.timecol].apply(self.time_to_seconds)
            if self.datecol is not None:
                time_deltas = X.sort_values(by=[self.idcol, self.datecol, 'time_seconds']).groupby([self.idcol, self.datecol])['time_seconds'].diff().fillna(3601)
                if (time_deltas < 3600).sum() > 0.1 * time_deltas.shape[0]:
                    self.num_features.append('TIME_daily_seconds_sin')
                    self.num_features.append('TIME_daily_seconds_cos')
            else:
                self.num_features.append('TIME_time_seconds')
                    
            self.cat_features.append('TIME_hour')
            self.num_features.append('TIME_hour_sin')
            self.num_features.append('TIME_hour_cos')
        if self.datecol is not None:
            dates = pd.to_datetime(X[self.datecol], format='%Y-%m-%d')
            date_range = (max(dates) - min(dates)).days
            if date_range > 366:
                self.cat_features.append('TIME_month')
            if date_range > 90:  
                self.cat_features.append('TIME_monthday')
                self.num_features.append('TIME_monthday_sin')
                self.num_features.append('TIME_monthday_cos')
            if date_range > 30:
                self.cat_features.append('TIME_weekday')
                self.num_features.append('TIME_weekday_sin')
                self.num_features.append('TIME_weekday_cos')
        self.cat_features = sorted(list(set(self.cat_features) - set(self.exclude_list)))
        self.num_features = sorted(list(set(self.num_features) - set(self.exclude_list)))


    def transform(self, X):
        if self.datecol is not None:
            if self.timecol is not None:
                timestamp = pd.to_datetime(X[self.datecol] + " " + X[self.timecol], format='%Y-%m-%d %H:%M:%S')
            else:
                timestamp = pd.to_datetime(X[self.datecol], format='%Y-%m-%d')
        elif self.timecol is not None:
            timestamp = pd.to_datetime(X[self.timecol], format='%H:%M:%S')

        if len({'TIME_daily_seconds_sin', 'TIME_daily_seconds_cos'} & set(self.num_features)) > 0:
            time_seconds = X[self.timecol].apply(self.time_to_seconds)

        if self.mode == 'cat' or self.mode == 'all':
            if 'TIME_ordercol_cat' in self.cat_features:
                X['TIME_ordercol_cat'] = X[self.ordercol] 

            if 'TIME_hour' in self.cat_features:
                X['TIME_hour'] =  timestamp.dt.hour

            if 'TIME_month' in self.cat_features:
                X['TIME_month'] =  timestamp.dt.month

            if 'TIME_monthday' in self.cat_features:
                X['TIME_monthday'] =  timestamp.dt.day

            if 'TIME_weekday' in self.cat_features:
                X['TIME_weekday'] =  timestamp.dt.weekday
            
        if self.mode == 'num' or self.mode == 'all':
            if 'TIME_ordercol_num' in self.num_features:
                X['TIME_ordercol_num'] =  self.scalers['TIME_ordercol_num'].transform(X[self.ordercol].values.reshape(-1, 1))

            if 'TIME_daily_seconds_sin' in self.num_features:
                X['TIME_daily_seconds_sin'] =  np.sin(2 * np.pi * time_seconds / (60 * 60 * 24))

            if 'TIME_daily_seconds_cos' in self.num_features:
                X['TIME_daily_seconds_cos'] =  np.cos(2 * np.pi * time_seconds / (60 * 60 * 24))

            if 'TIME_hour_sin' in self.num_features:
                X['TIME_hour_sin'] =  np.sin(2 * np.pi * timestamp.dt.hour.values / 24)

            if 'TIME_hour_cos' in self.num_features:
                X['TIME_hour_cos'] =  np.cos(2 * np.pi * timestamp.dt.hour.values / 24)

            if 'TIME_monthday_sin' in self.num_features:
                X['TIME_monthday_sin'] =  np.sin(2 * np.pi * timestamp.dt.day.values / 30)

            if 'TIME_monthday_cos' in self.num_features:
                X['TIME_monthday_cos'] =  np.cos(2 * np.pi * timestamp.dt.day.values / 30)

            if 'TIME_weekday_sin' in self.num_features:
                X['TIME_weekday_sin'] =  np.sin(2 * np.pi * timestamp.dt.weekday.values / 7)

            if 'TIME_weekday_cos' in self.num_features:
                X['TIME_weekday_cos'] =  np.cos(2 * np.pi * timestamp.dt.weekday.values / 7)

        return X

    def fit_transform(self, X):
        self.fit(X)
        return self.transform(X)

In [4]:
from ptls.preprocessing.time_preprocessing import TimePreprocessor

tp = TimePreprocessor(idcol='customer_id', 
                      ordercol='tr_datetime',
                      datecol='date', 
                      timecol='time',
                      mode='all')

In [5]:
tp.fit(a)

C:\Users\toppc\Documents\diploma\ptls-glove\ptls\preprocessing\time_preprocessing\preprocessor.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['time_seconds'] = X[self.timecol].apply(self.time_to_seconds)

In [6]:
a = tp.transform(a)

In [7]:
a

,Unnamed: 0,customer_id,tr_datetime,mcc_code,tr_type,amount,term_id,time,date,TIME_hour,...,TIME_weekday,TIME_ordercol_num,TIME_daily_seconds_sin,TIME_daily_seconds_cos,TIME_hour_sin,TIME_hour_cos,TIME_monthday_sin,TIME_monthday_cos,TIME_weekday_sin,TIME_weekday_cos
0,0,39026145,0.432940,4814,1030,-2245.92,NaN,10:23:26,2009-12-26,10,...,5,0.000947,0.408994,-0.912537,0.500000,-8.660254e-01,-7.431448e-01,0.669131,-0.974928,-0.222521
1,1,39026145,1.430197,6011,7010,56147.89,NaN,10:19:29,2010-11-04,10,...,3,0.003130,0.424660,-0.905353,0.500000,-8.660254e-01,7.431448e-01,0.669131,0.433884,-0.900969
2,2,39026145,1.431204,4829,2330,-56147.89,NaN,10:20:56,2009-08-18,10,...,1,0.003132,0.418924,-0.908021,0.500000,-8.660254e-01,-5.877853e-01,-0.809017,0.781831,0.623490
3,3,39026145,1.444375,5499,1010,-1392.47,NaN,10:39:54,2009-11-01,10,...,6,0.003161,0.342430,-0.939543,0.500000,-8.660254e-01,2.079117e-01,0.978148,-0.781831,0.623490
4,4,39026145,2.648403,5499,1010,-920.83,NaN,15:33:42,2010-05-31,15,...,0,0.005795,-0.803078,-0.595875,-0.707107,-7.071068e-01,2.079117e-01,0.978148,0.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6849341,6849341,61870738,453.668773,5499,1010,-5176.84,10217113,16:03:02,2009-11-19,16,...,3,0.992711,-0.872567,-0.488494,-0.866025,-5.000000e-01,-7.431448e-01,-0.669131,0.433884,-0.900969
6849342,6849342,61870738,454.454861,5411,1010,-1652.77,022915,10:54:60,2009-12-15,10,...,1,0.994431,0.279829,-0.960050,0.500000,-8.660254e-01,5.665539e-16,-1.000000,0.781831,0.623490
6849343,6849343,61870738,454.599988,5499,1010,-4687.23,10217113,14:23:59,2010-11-21,14,...,6,0.994749,-0.587726,-0.809060,-0.500000,-8.660254e-01,-9.510565e-01,-0.309017,-0.781831,0.623490
6849344,6849344,61870738,454.674919,5541,1110,-4491.83,RU570124,16:11:53,2009-12-15,16,...,1,0.994912,-0.890775,-0.454444,-0.866025,-5.000000e-01,5.665539e-16,-1.000000,0.781831,0.623490
6849345,6849345,61870738,454.754514,6011,7010,408756.67,372701,18:06:30,2010-07-14,18,...,2,0.995087,-0.999598,0.028358,-1.000000,-1.836970e-16,2.079117e-01,-0.978148,0.974928,-0.222521

In [166]:
b = pd.to_datetime(a.time, format='%H:%M:%S')

In [249]:
from datetime import timedelta
import random

c = [str(i + datetime.timedelta(days=random.randint(40000, 40600)))[:10] for i in b]

In [250]:
a['date'] = c

In [198]:
datetime.datetime.strptime(c[1], '%Y-%M-%d') - datetime.datetime.strptime(c[31223], '%Y-%M-%d')

datetime.timedelta(days=384, seconds=85920)

In [207]:
[datetime.datetime.strptime(i, '%Y-%M-%d') for i in c]

KeyboardInterrupt:

In [274]:
w = pd.to_datetime(a['date'] + " " + a['time'], format='%Y-%m-%d %H:%M:%S')

In [277]:
w.dt.hour

0          10
1          10
2          10
3          10
4          15
           ..
6849341    16
6849342    10
6849343    14
6849344    16
6849345    18
Length: 6849346, dtype: int32

In [210]:
d = pd.to_datetime(a['date'], format='%Y-%m-%d')

In [256]:
a['date'] + " " + a['time']

0          2009-07-11 10:23:26
1          2010-10-02 10:19:29
2          2011-01-11 10:20:56
3          2010-03-30 10:39:54
4          2010-02-05 15:33:42
                  ...
6849341    2011-02-12 16:03:02
6849342    2010-04-18 10:54:60
6849343    2010-04-10 14:23:59
6849344    2009-08-09 16:11:53
6849345    2010-08-27 18:06:30
Length: 6849346, dtype: object

In [239]:
a['time'].apply(lambda x: int(x[:2]))

0          10
1          10
2          10
3          10
4          15
           ..
6849341    16
6849342    10
6849343    14
6849344    16
6849345    18
Name: time, Length: 6849346, dtype: int64